version: "3.9"
services:
  quartz-db:
    image: postgres:14.0-alpine
    container_name: quartz-db
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DB: "${POSTGRES_DB_NAME}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - quartz-postgres:/var/lib/postgresql/data
  quartz-sessions:
    image: redis:6.2.5-alpine
    container_name: quartz-sessions
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - quartz-redis:/data
volumes:
  quartz-postgres:
  quartz-redis:
